services:
  - type: web
    name: sail-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PORT
        value: 10000
